In [1]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
   a.append(random.random())
print('随机完毕')
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a) # 转换为ndarray
print('转换完毕')
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

随机完毕
转换完毕
1.4388360977172852 0.21772503852844238


In [2]:
t1 = np.array([1,2,3]) 
print(t1) 
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(type(range(10))) # range返回的是一个range对象，不能直接转换为ndarray
t2 = np.array(range(10))
print(t2) 
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
t3 = np.arange(0,10,2) # 等价于range(0,10,2),返回ndarray
print(t3) 
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [5]:
#二维列表转ndarray
import numpy as np
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2) #列表的输出是有逗号的，ndarray的输出是没有逗号的

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [6]:
twoArray.tolist() # ndarray转换为列表

[[1, 2], [3, 4], [5, 6]]

In [7]:
#看ndarray的各种属性
list2 = [[1,2],[3,4],[5,6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype) #默认int32

2
(3, 2)
6
int64


In [8]:
four = np.array([[1,2,3],[4,5,6]])

print(four)
# 修改的是原有的
four1=four
print(id(four))
four.shape = (3,2)  # 改变形状
print(id(four))
print(id(four1))
print(four)

[[1 2 3]
 [4 5 6]]
4581963120
4581963120
4581963120
[[1 2]
 [3 4]
 [5 6]]


In [9]:
#将数组转换为列表 tolist
a= np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist() 
print(list_a) 
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


In [10]:
import random
f = np.array([1,2,3,4,5], dtype = np.int16) # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize) # 1 np.int16(一个字节)
# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(np.int64) 
print(f1.dtype)
print(f1.itemsize)  #显示字节数

2
int16
int64
8


In [11]:
t1 = np.arange(24).reshape((6,4))
print(t1)
print("-"*20)
t2=t1.tolist()
print(t1+2)
# print(t2+2) 不能对列表进行直接加整数操作
print("-"*20)
print(t1*2) 
print("-"*20)
print(t1/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [12]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1)
print(t2)
print(t1+t2) 
print(t1*t2)  #是否是矩阵乘法？不是

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [13]:
t1 = np.arange(24).reshape((4,6)) 
t2 = np.arange(6).reshape((1,6))
print(t2.shape)
print(t1)
print(t2)
t1-t2

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [14]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a,axis=0)) # [5 7 9]，按哪个轴求和，哪个轴没了
print("-"*20)
print(np.sum(a,axis=1)) # [ 6 15]
print("-"*20)
print(np.sum(a))
print("-"*20)

[[1 2 3]
 [4 5 6]]
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [15]:
a = np.arange(27).reshape((3, 3, 3))
print(a)
print("-" * 20)
b = np.sum(a, axis=0)
print("-" * 20)
print(b)
c = np.sum(a, axis=1)
print("-" * 20)
print(c)
d = np.sum(a, axis=2)
print("-" * 20)
print(d)
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print("-" * 20)
print(b.shape)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)
