In [1]:
import numpy as np

In [2]:
a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:7:2])

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [3]:
t1 = np.arange(24).reshape(4,6)
print(t1)
print('-'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('-'*20)
print(t1[1:])# 取连续的多行
print('-'*20)
print(t1[1:3,:])# 取连续的多行
print('-'*20)
print(t1[[0,2,3]])# 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[ 6  7  8  9 10 11]
--------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [5]:
t2 = np.arange(24).reshape(4,6)
t2[[0,2,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列  py是t1[2][3]
print('*'*20)
print(t1[[0,1,1],[0,1,3]])# 取多个不连续的值，[[行，行。。。],[列，列。。。]]

[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]


# 修改数组的值