# 6 Pandas的函数应用

In [1]:
import pandas as pd
import numpy as np
# Numpy ufunc 函数，randn跟的是维数
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)

print(np.abs(df)) #绝对值

          0         1         2         3
0 -1.207255 -0.228082 -0.645468 -1.737784
1 -2.007319 -1.773175 -0.611317 -0.810143
2 -2.690278 -0.267494  0.235944 -1.817938
3 -2.671815 -1.047553  0.153013  0.058026
4 -0.205010  0.656965 -0.813280 -2.017485
          0         1         2         3
0  1.207255  0.228082  0.645468  1.737784
1  2.007319  1.773175  0.611317  0.810143
2  2.690278  0.267494  0.235944  1.817938
3  2.671815  1.047553  0.153013  0.058026
4  0.205010  0.656965  0.813280  2.017485


In [3]:
#apply默认作用在列上,x是每一列,因为axis=0
print(df.apply(lambda x : x.max(), axis=0))

0    1.087995
1    0.434726
2    0.711669
3    0.329257
dtype: float64


In [4]:
#apply作用在行上
print(df.apply(lambda x : x.max(), axis=1))

0   -0.351662
1    0.329257
2   -0.422633
3    1.087995
4    0.050864
dtype: float64


In [5]:
'%.2f' % 1.234

'1.23'

In [12]:
# 使用applymap应用到每个数据
df2=df.map(lambda x : float('%.2f' % x))
df2

0     1     2     3
0 -2.71 -1.13 -1.29 -0.35
1 -1.12 -0.73 -1.14  0.33
2 -0.99 -0.42 -1.19 -1.37
3  1.09  0.43  0.71 -1.29
4 -2.11 -0.45  0.05 -0.74

In [5]:
type('%.2f' % 1.3456)

str

## 6.4 索引排序

In [2]:
# Series
print(np.random.randint(5, size=5))
s4 = pd.Series(range(10, 15), index = np.random.randint(5, size=5)) #索引随机生成
print(s4)
print('-'*50)
# 索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print(s4)
# s4.loc[0:3]  loc索引值不唯一时直接报错
print(s4.iloc[0:3])
s4[0:3]  #默认用的位置索引

[2 1 2 2 4]
0    10
2    11
3    12
2    13
0    14
dtype: int64
--------------------------------------------------
0    10
0    14
2    11
2    13
3    12
dtype: int64
0    10
2    11
3    12
2    13
0    14
dtype: int64
0    10
2    11
3    12
dtype: int64


0    10
2    11
3    12
dtype: int64

In [8]:
# s4.loc[1:2] #loc索引值唯一时可以切片

In [3]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5),
                   index=np.random.randint(5, size=5),
                   columns=np.random.randint(5, size=5))
print(df4)
#轴零是行索引排序
df4_isort = df4.sort_index(axis=0, ascending=False)
print(df4_isort)


          4         2         1         4         3
0  0.290356 -0.928574  1.326263 -0.376125 -0.222534
1  0.664712  1.878370  0.922800  1.281062 -0.347827
3  0.441859  1.227592  0.405797  2.634434  0.469048
4  0.239610 -0.653958 -0.239987 -1.672604  0.447063
3  1.857909 -0.772407  2.903085 -0.467319 -0.025959
          4         2         1         4         3
4  0.239610 -0.653958 -0.239987 -1.672604  0.447063
3  0.441859  1.227592  0.405797  2.634434  0.469048
3  1.857909 -0.772407  2.903085 -0.467319 -0.025959
1  0.664712  1.878370  0.922800  1.281062 -0.347827
0  0.290356 -0.928574  1.326263 -0.376125 -0.222534


In [4]:
#轴1是列索引排序
df4_isort = df4.sort_index(axis=1, ascending=True)
print(df4_isort)

          1         2         3         4         4
0  1.326263 -0.928574 -0.222534  0.290356 -0.376125
1  0.922800  1.878370 -0.347827  0.664712  1.281062
3  0.405797  1.227592  0.469048  0.441859  2.634434
4 -0.239987 -0.653958  0.447063  0.239610 -1.672604
3  2.903085 -0.772407 -0.025959  1.857909 -0.467319


# 6.5 按值排序

In [5]:
# 按值排序,by后是column的值
import random
l=[random.randint(0,100) for i in range(24)] #生成24个随机数
df4 = pd.DataFrame(np.array(l).reshape(6,4)) #生成6行4列的dataframe
print(df4.values) #查看数据,ndarray
print('-'*50)
print(df4)
print('-'*50)
#按轴零排序，by后是列名,交换的是行
df4_vsort = df4.sort_values(by=3,axis=0, ascending=False) #寻找的是columns里的3,重要
print(df4_vsort)


[[36  0 74 84]
 [46 85 33 63]
 [93 48 13 35]
 [47 25 98 67]
 [71 95 79 30]
 [67 43 93 77]]
--------------------------------------------------
    0   1   2   3
0  36   0  74  84
1  46  85  33  63
2  93  48  13  35
3  47  25  98  67
4  71  95  79  30
5  67  43  93  77
--------------------------------------------------
    0   1   2   3
0  36   0  74  84
5  67  43  93  77
3  47  25  98  67
1  46  85  33  63
2  93  48  13  35
4  71  95  79  30


In [6]:
#按轴1排序，by后行索引名，交换的是列,使用场景少
df4_vsort = df4.sort_values(by=3,axis=1, ascending=False) #寻找的是index里的3
print(df4_vsort)

    2   3   0   1
0  74  84  36   0
1  33  63  46  85
2  13  35  93  48
3  98  67  47  25
4  79  30  71  95
5  93  77  67  43


# 6.6 处理缺失数据

处理缺失，要么删，要么填充

In [7]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0         1         2
0 -0.253604  0.295339 -0.564874
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000


In [8]:
df_data.iloc[2,0]

nan

In [9]:
#isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


## 删除缺失数据

In [10]:
#默认一个样本，任何一个特征缺失，就删除
#inplace True是修改的是原有的df
#subset=[0]是指按第一列来删除,第一列有空值就删除对应的行
print(df_data.dropna())
# df_data

          0         1         2
0 -0.253604  0.295339 -0.564874
3  1.000000  2.000000  3.000000


In [11]:
df_data

0         1         2
0 -0.253604  0.295339 -0.564874
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [12]:
#某个特征缺失太多时，才删除
print(df_data.dropna(axis=1))  #某列由nan就删除该列

          1
0  0.295339
1  2.000000
2  4.000000
3  2.000000


In [13]:
df_data

0         1         2
0 -0.253604  0.295339 -0.564874
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

## 填充缺失数据

In [14]:
#给零列的空值填为-100，按特征（按列）去填充。（一般填均值，中位数，众数）
print(df_data.iloc[:,0].fillna(-100.))
df_data

0     -0.253604
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64


0         1         2
0 -0.253604  0.295339 -0.564874
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [16]:
df_data.columns

RangeIndex(start=0, stop=3, step=1)

In [15]:
#依次拿到每一列
for i in df_data.columns:
    print(df_data.loc[:,i])

0   -0.253604
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
0    0.295339
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
0   -0.564874
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64
